### ISSUE TITLE
[DOC][CRM REPORT]

### ISSUE THREAD

**Issue by ghost** [oroinc/documentation#240]
On the cookbook, there is this : https://www.orocrm.com/documentation/2.3/cookbook/entities/report#cookbook-entities-report-grid

But it doesn't work, because now, we have to use something like this : 

For datagrid :
```yml
#vendor/oro/crm/src/Oro/Bundle/ReportCRMBundle/Resources/config/oro/datagrids.yml
 oro_reportcrm-accounts-life_time_value:
        pageTitle: oro.reportcrm.accounts_life_time_value
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                select:
                    - a.id
                    - a.name
                    - SUM( CASE WHEN lifetimeHistory.amount is NULL THEN 0 ELSE lifetimeHistory.amount END ) as value
                from:
                    - { table: OroAccountBundle:Account, alias: a }
                join:
                    left:
                        - { join: OroChannelBundle:LifetimeValueHistory, alias: lifetimeHistory, conditionType: WITH, condition: "lifetimeHistory.account = a and lifetimeHistory.status = true" }
                groupBy:  a.id
        columns:
            name:   { label: oro.reportcrm.datagrid.columns.account_name }
            value:  { label: oro.account.lifetime_value.label,  frontend_type: currency }
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_account_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_account_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    name:
                        label: oro.magento.datagrid.columns.page_total

            grand_total:
                columns:
                    name:
                        label: oro.magento.datagrid.columns.grand_total
                    value:
                        expr: SUM( CASE WHEN lifetimeHistory.amount is NULL THEN 0 ELSE lifetimeHistory.amount END )
                        formatter: currency
        sorters:
            columns:
                name:   { data_name: a.name }
                value:  { data_name: value }
        filters:
            columns:
                name:
                    type: string
                    data_name: a.name
                value:
                    type:             currency
                    data_name:        value
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        options:
            entityHint: report data
            export: true
            entity_pagination: true
```

For navigation :
```yml           
#vendor/oro/crm/src/Oro/Bundle/ReportCRMBundle/Resources/config/oro/navigation.yml accounts_by_opportunities:
                label: 'oro.reportcrm.menu.accounts_by_opportunities.label'
                route: 'oro_reportcrm_index'
                route_parameters:
                    reportGroupName: 'accounts'
                    reportName:      'by_opportunities'
```

So in datagrid, it's miss, the "pageTitile" and in navigation it's we have to replace this
```yml
route: orocrm_report_index
            routeParameters:
                reportGroupName: tasks
                reportName: by_priority
```
by something like this  :
```yml
           route: 'oro_reportcrm_index'
             route_parameters:
                reportGroupName: tasks
                reportName: by_priority
```
